import { ConsultationPricingTier, SiteSettings } from "./types";

export const SITE_SETTINGS: SiteSettings = {
  brandName: "Astro Raj",
  tagline: "Vedic Astrology & Spiritual Guidance",
  astrologerName: "Astrologer Rajat Thakur",
  phone: "+91 6398-754093",
  cleanPhone: "+916398754093",
  whatsappNumber: "916398754093",
  whatsappMessage: "Hari Om Guruji! I would like to inquire about booking a Vedic astrology consultation.",
  email: "info@astroraj.org",
  address: "Shisham Jhari, near Hemkund Sahib Gurudwara, Muni Ki Reti, Rishikesh, Uttarakhand 249137, India",
  mapEmbedUrl: "https://maps.google.com/maps?q=Shisham+Jhari+Muni+Ki+Reti+Rishikesh&t=&z=15&ie=UTF8&iwloc=&output=embed",
  experienceYears: 12,
  clientsServedCount: "10,000+",
  kundlisAnalyzedCount: "200,000+",
  officeHours: "Monday to Sunday: 9:00 AM - 8:00 PM IST",
  socialLinks: {
    facebook: "https://facebook.com/astroraj",
    instagram: "https://instagram.com/astroraj",
    youtube: "https://youtube.com/@astroraj",
  },
  gaMeasurementId: "G-Y1SNGX3FBX",
};

// Official Consultation Pricing Matrix from AstroRaj
export const CONSULTATION_PRICING_MATRIX: ConsultationPricingTier[] = [
  {
    id: "audio-15-normal",
    durationMinutes: 15,
    type: "audio",
    urgency: "normal",
    turnaroundDays: "7–15 Days",
    price: 2100,
    originalPrice: 4200,
  },
  {
    id: "audio-15-urgent",
    durationMinutes: 15,
    type: "audio",
    urgency: "urgent",
    turnaroundDays: "Within 24 Hours",
    price: 4200,
    originalPrice: 8400,
  },
  {
    id: "audio-30-normal",
    durationMinutes: 30,
    type: "audio",
    urgency: "normal",
    turnaroundDays: "7–15 Days",
    price: 3100,
    originalPrice: 6200,
  },
  {
    id: "audio-30-urgent",
    durationMinutes: 30,
    type: "audio",
    urgency: "urgent",
    turnaroundDays: "Within 24 Hours",
    price: 6200,
    originalPrice: 12400,
  },
  {
    id: "video-15-normal",
    durationMinutes: 15,
    type: "video",
    urgency: "normal",
    turnaroundDays: "7–15 Days",
    price: 3100,
    originalPrice: 6200,
  },
  {
    id: "video-15-urgent",
    durationMinutes: 15,
    type: "video",
    urgency: "urgent",
    turnaroundDays: "Within 24 Hours",
    price: 6200,
    originalPrice: 12400,
  },
  {
    id: "video-30-normal",
    durationMinutes: 30,
    type: "video",
    urgency: "normal",
    turnaroundDays: "7–15 Days",
    price: 5100,
    originalPrice: 10200,
  },
  {
    id: "video-30-urgent",
    durationMinutes: 30,
    type: "video",
    urgency: "urgent",
    turnaroundDays: "Within 24 Hours",
    price: 10200,
    originalPrice: 20400,
  },
];

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "About Guruji", href: "/about" },
  {
    label: "Services",
    href: "/services",
    submenu: [
      { label: "Astrology Consultation", href: "/services/astrology-consultation", description: "Career, Marriage, Kundli & Life Path analysis" },
      { label: "Online Puja Services", href: "/services/online-puja", description: "Authentic Vedic havans & Shri Vidya rituals" },
      { label: "Certified Gemstones", href: "/services/gemstones", description: "Individual planetary gemstone recommendation & energization" },
      { label: "Ayurveda & Wellness", href: "/services/ayurveda", description: "Traditional herbal remedies & holistic health guidance" },
    ],
  },
  { label: "Kundli", href: "/kundli" },
  { label: "Shop", href: "/shop" },
  { label: "Blog", href: "/blog" },
  { label: "Contact", href: "/contact" },
];
